### ISSUE TITLE
Ylimääräiset henkilöt

### ISSUE THREAD

**Issue by joakimgrr** [sysart/sysart.fi-react#5]
Arto Virtanen ja Sami Klaavu löytyvät henkilöistä. Voi poistaa, koska eivät ole enää meillä töissä.

**Comment by PekkaAstala** [comment]
Allekirjoittanut puuttuu henkilöistä. Voi lisätä, koska on meillä töissä.

**Comment by heikkipesonen** [comment]
minä puutun henkilöistä, voi jättää pois koska olen jurpo
